### ISSUE TITLE
Beta label

### ISSUE THREAD

**Issue by relisyse** [Financial-Times/o-labels#24]
To label sections of the site which will be released as beta features. 
May require updating O-header. 

Desktop size:
box dimensions
W75 H20
outline colour #CCC0B7

Font - Metric
Weight - Medium
Size - 16
O-typography scale - 0

Mobile:
to be confirmed

![graphics-betaflag](https://user-images.githubusercontent.com/39570434/46612127-946a3c80-cb07-11e8-8ac5-f1e31ac4da72.jpg)
![graphics-burger-betaflag](https://user-images.githubusercontent.com/39570434/46612129-97fdc380-cb07-11e8-92da-ea075ff357af.jpg)

**Comment by rowanmanning** [comment]
Update on this, @OttlikG and I are going to work on and release this on Monday (15th)
