### ISSUE TITLE
Consider including the "new" label

### ISSUE THREAD

**Issue by rowanmanning** [Financial-Times/o-labels#53]
Jono presented new content indicators in the UXD Show & Tell, and highlighted that the "new" label used in teasers and across other parts of FT.com is inconsistent. I think there might be a case for a new type of label:

<img width="504" alt="A screenshot of the 'new' label in use" src="https://user-images.githubusercontent.com/138944/65685011-e5e14380-e058-11e9-84f1-88f0bb7e9dfc.png">

This currently lives in o-teaser and probably has been reimplemented across FT.com. Possibly an opportunity for us to reduce some repetition here. I'll try and attach some more screenshots.

Note to self: potentially named "indicator label"?

**Comment by rowanmanning** [comment]
An update based on a conversation in Slack: we have the following places where we use the word "new" in isolation. This probably needs addressing.

## 1. Recently published articles

I don't think this red dot was ever intended to be used for this purpose, from Origami's perspective. I think the work has happened outside of o-teaser and it repurposes the style of "live" articles.

<img width="1241" alt="Screenshot 2019-09-26 at 13 26 51" src="https://user-images.githubusercontent.com/138944/65689969-f64beb00-e065-11e9-8c71-baafecd97e62.png">
<img width="783" alt="Screenshot 2019-09-26 at 13 27 29" src="https://user-images.githubusercontent.com/138944/65689977-f8ae4500-e065-11e9-9e32-833474283915.png">

## 2. Articles that are new to the current user

This uses o-labels, but it doesn't exist in Origami – the teal label is custom. I'm not sure about the choice as we use the same teal for primary buttons.

<img width="391" alt="Screenshot 2019-09-26 at 13 26 16" src="https://user-images.githubusercontent.com/138944/65690025-1085c900-e066-11e9-8b29-34a8cd8f9eb6.png">

## 3. New website features

This uses o-labels, but the "commercial" variant which is supposed to indicate content that has been payed for by someone else. This feels like a misuse.

<img width="574" alt="Screenshot 2019-09-26 at 13 42 08" src="https://user-images.githubusercontent.com/138944/65690044-1bd8f480-e066-11e9-8962-f8c558a05ab4.png">

**Comment by rowanmanning** [comment]
Another _kind_ of related thing, does the beta label kind of fit with the "new product" type label?

<img width="849" alt="Screenshot 2019-11-08 at 11 07 30" src="https://user-images.githubusercontent.com/138944/68472328-27e4d400-0218-11ea-9f53-2a1ed0014ce6.png">

**Comment by notlee** [comment]
Note: We have indicator labels now for recently published articles, but haven't considered the other cases

**Comment by chee** [comment]
I'm going to close this, because I think the indicator label pr #80 solves the initial reason for opening the PR.
